/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-10-28 18:58:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class areaVendas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("	<meta charset=\"ISO-8859-1\">\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./Estilos/style.css\">\r\n");
      out.write("\r\n");
      out.write("	<title>Area de Vendas</title>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 <div class=\"container-geral-3\">\r\n");
      out.write("        <div class=\"container-porta-cards-2\">\r\n");
      out.write("            \r\n");
      out.write("            <h1>Produtos</h1>           \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Pastel</h3>\r\n");
      out.write("                <img src=\"https://cdn.rawgit.com/srpastel/sr/9b393b48/pastel1.png?raw=true\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Coxinha</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/4727/4727229.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Pizza</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/3132/3132693.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Pão de queijo</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/3038/3038054.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Sanduiche</h3>\r\n");
      out.write("                <img src=\"https://cdn.icon-icons.com/icons2/1447/PNG/512/32386sandwich_98891.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Hot Dog</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/4803/4803052.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Croissant</h3>\r\n");
      out.write("                <img src=\"https://assets.stickpng.com/images/611951a7f8fe340004e0d2e9.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Hamburgão</h3>\r\n");
      out.write("                <img src=\"https://i.pinimg.com/originals/37/1d/c4/371dc4c654bd99ec1a9fb638d548da2d.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Mix de frutas</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/1475/1475906.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Bolo</h3>\r\n");
      out.write("                <img src=\"https://images.vexels.com/media/users/3/134783/isolated/preview/a3fee4ad85569456d4927a70576ffb5f-torta-de-bolo-de-fatia.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Refrigerante</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/3082/3082015.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                \r\n");
      out.write("                <h3>Suco</h3>\r\n");
      out.write("                <img src=\"https://cdn-icons-png.flaticon.com/512/5488/5488411.png\" alt=\"\">  \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"container-lista-vendas\">\r\n");
      out.write("            <h1>Itens da venda</h1>\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>                        \r\n");
      out.write("                        <th>Produto</th>\r\n");
      out.write("                        <th>Preço</th>                        \r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <td>Pastel</td>\r\n");
      out.write("                        <td>R$ 5,00</td>\r\n");
      out.write("                        <td class=\"bExcluir\"><button class=\"excluir\">\r\n");
      out.write("                            <img src=\"https://th.bing.com/th/id/R.9a24860eb0a8bf43441e08f3dff18629?rik=mFXXFJD796yXBg&riu=http%3a%2f%2fclipart-library.com%2fimages_k%2fx-mark-transparent-background%2fx-mark-transparent-background-20.png&ehk=kxREAhxDwr4oGTxKV64H2%2bmLVl2vg10OlOFZqDCKSj8%3d&risl=&pid=ImgRaw&r=0\" alt=\"\">\r\n");
      out.write("                        </button></td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <td>Pastel</td>\r\n");
      out.write("                        <td>R$ 5,00</td>\r\n");
      out.write("                        <td class=\"bExcluir\"><button class=\"excluir\"><img src=\"https://th.bing.com/th/id/R.9a24860eb0a8bf43441e08f3dff18629?rik=mFXXFJD796yXBg&riu=http%3a%2f%2fclipart-library.com%2fimages_k%2fx-mark-transparent-background%2fx-mark-transparent-background-20.png&ehk=kxREAhxDwr4oGTxKV64H2%2bmLVl2vg10OlOFZqDCKSj8%3d&risl=&pid=ImgRaw&r=0\" alt=\"\"></button></td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("                <tfoot>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>Total</td>\r\n");
      out.write("                        <td>R$ 10,00</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tfoot>\r\n");
      out.write("            </table>\r\n");
      out.write("            \r\n");
      out.write("        </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
