/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-11-03 21:29:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import controller.Usuario_controler;
import Controler.Perfil_controler;
import java.sql.ResultSet;
import Modelo.Usuario;

public final class cad_005fusuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controller.Usuario_controler");
    _jspx_imports_classes.add("Controler.Perfil_controler");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("Modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Cadastro de Usuários</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form method=\"post\" id=\"fUsuario\">\r\n");
      out.write("    	<div id=\"divUsuario\">\r\n");
      out.write("  			<label>Selecione um usuário para alterar ou excluir: </label>\r\n");
      out.write("  			<hr>\r\n");
      out.write("			<select id=\"cbUsuario\" name=\"cbUsuario\">\r\n");
      out.write("				<option value=\"\" disabled selected>-- Selecione um usuário --</option>\r\n");
      out.write("			");

				ResultSet usuarios = Usuario_controler.consultar();
				while(usuarios.next()){
					out.print("<option value=" + usuarios.getInt("cod_usuario") + ">" + usuarios.getString("nome_usuario") + "</option>");
				}
			
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"divNovo\">\r\n");
      out.write("			<h1>Cadastrar novo Usuário</h1>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<label>Informe seu nome:</label>\r\n");
      out.write("			<input id=\"inpNome\" name=\"inpNome\" type=\"text\" placeholder=\"Informe seu nome\">\r\n");
      out.write("			<hr>\r\n");
      out.write("			<label>Informe seu email:</label>\r\n");
      out.write("			<input id=\"inpEmail\" name=\"inpEmail\" type=\"text\" placeholder=\"Informe seu email\">\r\n");
      out.write("			<hr>\r\n");
      out.write("			<label>Informe seu telefone:</label>\r\n");
      out.write("			<input id=\"inpFone\" name=\"inpFone\" type=\"text\" placeholder=\"Informe seu telefone\">\r\n");
      out.write("			<hr>\r\n");
      out.write("			<label>Selecione um perfil: </label>\r\n");
      out.write("				<select id=\"cbPerfil\" name=\"cbPerfil\">\r\n");
      out.write("					<option value=\"\" disabled selected>-- Selecione um perfil --</option>\r\n");
      out.write("					");

						ResultSet perfis = Perfil_controler.consultar();
							while(perfis.next()){
								out.print("<option value=" + perfis.getInt("cod_perfil") + ">" + perfis.getString("nome_perfil") + "</option>");
							}
					
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("				<hr>\r\n");
      out.write("		</div>  	   	   \r\n");
      out.write("    		<button onclick=\"Inserir()\">Gravar</button>		\r\n");
      out.write("    		<button onclick=\"Alterar()\">Alterar</button>\r\n");
      out.write("    		<button onclick=\"Excluir()\">Excluir</button>\r\n");
      out.write("	</form>	  \r\n");
      out.write("	<script>\r\n");
      out.write("	function Inserir(){\r\n");
      out.write("		let nome = document.getElementById(\"inpNome\");\r\n");
      out.write("		if (nome.value == \"\") {\r\n");
      out.write("			alert(\"Informe o nome do usuário\");\r\n");
      out.write("			nome.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		let email = document.getElementById(\"inpEmail\");\r\n");
      out.write("		if (email.value == \"\") {\r\n");
      out.write("			alert(\"Informe o email do usuário\");\r\n");
      out.write("			email.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		let fone = document.getElementById(\"inpFone\");\r\n");
      out.write("		if (fone.value == \"\") {\r\n");
      out.write("			alert(\"Informe o telefone do usário\");\r\n");
      out.write("			fone.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		let perf = document.getElementById(\"cbPerfil\");\r\n");
      out.write("		if (perf.value == \"\") {\r\n");
      out.write("			alert(\"Selecione um perfil\");\r\n");
      out.write("			perf.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		SetAction(\"inserir\");\r\n");
      out.write("		document.getElementById(\"fUsuario\").submit();\r\n");
      out.write("	}	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function Alterar(){\r\n");
      out.write("			let usu = document.getElementById(\"cbUsuario\");\r\n");
      out.write("			if (usu.value == \"\") {\r\n");
      out.write("				alert(\"Selecione um usuário\");\r\n");
      out.write("				usu.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			let nome = document.getElementById(\"inpNome\");\r\n");
      out.write("			if (nome.value == \"\") {\r\n");
      out.write("				alert(\"Informe o nome do usuário\");\r\n");
      out.write("				nome.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			let email = document.getElementById(\"inpEmail\");\r\n");
      out.write("			if (email.value == \"\") {\r\n");
      out.write("				alert(\"Informe o email do usuário\");\r\n");
      out.write("				email.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			let fone = document.getElementById(\"inpFone\");\r\n");
      out.write("			if (fone.value == \"\") {\r\n");
      out.write("				alert(\"Informe o telefone do usário\");\r\n");
      out.write("				fone.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			let perf = document.getElementById(\"cbPerfil\");\r\n");
      out.write("			if (perf.value == \"\") {\r\n");
      out.write("				alert(\"Selecione o perfil\");\r\n");
      out.write("				\r\n");
      out.write("				perf.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			SetAction(\"alterar\");\r\n");
      out.write("			document.getElementById(\"fUsuario\").submit();\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			function Excluir(){\r\n");
      out.write("				let usu = document.getElementById(\"cbUsuario\");\r\n");
      out.write("				if (usu.value == \"\") {\r\n");
      out.write("					alert(\"Selecione um usuário\");\r\n");
      out.write("					usu.focus();\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("			SetAction(\"excluir\");\r\n");
      out.write("			document.getElementById(\"fUsuario\").submit();\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("						\r\n");
      out.write("	function SetAction(operacao) {\r\n");
      out.write("		let form = document.getElementById(\"fUsuario\");\r\n");
      out.write("		form.setAttribute(\"action\", \"Usuario_Banco.jsp?op=\" + operacao);\r\n");
      out.write("	}\r\n");
      out.write("		</script>  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
